ekf_filter_node:
  ros__parameters:
    frequency: 30.0 # hz/updates per sec
    publish_acceleration: true
    publish_tf: true

    # important: set the {map, odom, base_link, world}_frames...
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
