slam_toolbox:
  ros__parameters:
    # make the queue size muuuuch bigger
    # TODO(bray): can u... even do this for a tf frame???
    # qos_overrides./sensors/depth_image/camera_info.publisher.depth: 100

    # tell the program to actually perform mapping
    mode: mapping

    # required: publish the map frame on `/tf` topic!
    publish_tf: true
    publish_tf_rate: 20.0

    # define tf2 frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # ask it to use a specific solver
    solver_plugin: solver_plugins::CeresSolver

    # other conf.
    map_update_interval: 1.0
    transform_tolerance: 0.1
    max_laser_range: 30.0
    z_hit: 0.95
    z_rand: 0.05
    sigma_hit: 0.2

    # toggle for better debugging
    debug_logging: true
