[package]
name = "geographic_msgs"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
safe_drive = { version = "0.4.3", default-features = false, features = ["humble"] }
geometry_msgs = { path = "/home/barrett/auto_ros2/src/custom_interfaces/bindings/geometry_msgs" }
std_msgs = { path = "/home/barrett/auto_ros2/src/custom_interfaces/bindings/std_msgs" }
unique_identifier_msgs = { path = "/home/barrett/auto_ros2/src/custom_interfaces/bindings/unique_identifier_msgs" }
