services:
  soro:
    image: ros2-soro
    container_name: soro
    ports:
      - "5901:5901"
      - "5801:5801"
    environment:
      - AUTO_ROS2_REPO_LOCATION
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # mount the `auto_ros2` repo from your computer
      - type: bind
        source: ${AUTO_ROS2_REPO_LOCATION}
        target: /home/soro/auto_ros2
        read_only: false
        bind:
          propagation: rprivate
          selinux: Z
