# this file controls the IMU only.
#
# it'd also work for any wheel odometry sensors (to see how much we've "really"
# moved), but we don't have those as of writing!

ekf_filter_node_odom:
  ros__parameters:
    # behavior
    two_d_mode: true
    publish_tf: true

    # frame parameters
    base_link_frame: base_link
    world_frame: odom

    # configure the imu to only give heading for local usage
    imu0: /sensors/imu
    imu0_config:
      [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ]
