# this file controls the GPS odometry available to dependent nodes.
#
# in particular, it's required for the global ekf outputs, and is used in the
# `global_odom` file's `ekf_filter_node_map` node.

/**:
  ros__parameters:
    qos_overrides:
      /odometry/filtered:
        subscription:
          reliability: reliable
          history: keep_last
          depth: 10
          durability: volatile

    # timing
    frequency: 30.0
    delay: 3.0

    # behavior
    enable: true
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    use_odometry_yaw: false

    # node rules
    broadcast_cartesian_transform: false
    publish_filtered_gps: true
    wait_for_datum: false
