# this file controls the GPS odometry available to dependent nodes.
#
# in particular, it's required for the global ekf outputs, and is used in the
# `global_odom` file's `ekf_filter_node_map` node.

/**:
  ros__parameters:
    qos_overrides:
      /odometry/filtered:
        subscription:
          reliability: reliable
          history: keep_last
          depth: 10
          durability: volatile

    # timing
    frequency: 30.0
    delay: 3.0

    # behavior
    enable: true
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    use_odometry_yaw: false

    # node rules
    #
    # ... this puts the utm frame in the chain. we need it to translate
    # ... coordinates into map-local values
    broadcast_cartesian_transform: true
    broadcast_cartesian_transform_as_parent_frame: false
    publish_filtered_gps: true
    wait_for_datum: false

    # frame config
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    earth_frame: earth
